### ISSUE TITLE
Start up after interruption

### ISSUE THREAD

**Issue by surgebiswas** [surgebiswas/transcriptome_compression#4]
If it's determined that the output folder exists but the appropriate output is not there (i.e. the process was interrupted during this download/quantification), the directory should be first deleted, and then the process should begin from anew.

**Comment by FriendlyNeighborhoodNematode** [comment]
subroutine &already_processed will now check if the folder already exists. if it doesnt, returns 0. if it does, it checks if the file quant_bias_corrected.sf (usually created very late in the sailfish pipeline) exists. if it does, returns 1. if it doesnt, recursively removes run directory tree including folder and returns 0. using function remove_tree() from perl module File::Path (implemented into perl since 5.9.5) to avoid an rm -r command in an automated script.

sub already_processed {

```
my $processed = 0;
my $rundir = shift @_;
my @files_in_rundir;

if (-d "$out/$run/") {

    opendir DIR, "$out/$run/" or print "cannot open directory $out/$rundir\n";
    @files_in_rundir = grep { $_ ne '.' && $_ ne '..' } readdir DIR;
    closedir DIR;

    for my $file_in_rundir (@files_in_rundir) {

        if ($file_in_rundir =~ /quant_bias_corrected.sf/) {
            $processed = 1;
        }
    }
    if ($processed == 0) {
        print "Run $run exists, but did not finish sucessfully. resetting run and retrying . . .\n";
        remove_tree( "$out/$run/", {save => 1} ) if $EXECUTE;
    }
}
return $processed;
```

}
